### ISSUE TITLE
Windows: Boilerplate copies boilerplate.yml when it shouldn't.

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/boilerplate#3]
```
PS C:\tools> boilerplate --template-folder C:\tools\boilerplate --output-folder C:\tools\output

[boilerplate] 2016/08/08 14:42:31 Loading boilerplate config from C:\tools\boilerplate/boilerplate.yml
Enter a value for variable 'Title': Hello
Enter the welcome text for the website: Welcome!
Should the website show the logo? (default: 'true'): false
[boilerplate] 2016/08/08 14:42:36 Processing templates in C:\tools\boilerplate and outputting generated files to C:\tools\output
[boilerplate] 2016/08/08 14:42:36 Skipping C:\tools\boilerplate
[boilerplate] 2016/08/08 14:42:36 Copying C:\tools\boilerplate\boilerplate.yml to C:\tools\output/boilerplate.yml
[boilerplate] 2016/08/08 14:42:36 Processing template C:\tools\boilerplate\index.html and writing to C:\tools\output/index.html
```

Note the following line:

```
[boilerplate] 2016/08/08 14:42:36 Copying C:\tools\boilerplate\boilerplate.yml
```

Boilerplate is supposed to ignore this file (and possibly other files), but appears not to do so on Windows.

**Comment by josh-padnick** [comment]
@brikis98 I believe this is now resolved?

**Comment by brikis98** [comment]
This doesn't happen on *nix, and I haven't made any changes or tested on Windows, so I'm guessing it's still an issue.

**Comment by josh-padnick** [comment]
Ah, missed the Windows-only part. Yep, you're right.
